# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1196, 1062)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: #E3E3E3;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setStyleSheet("image: url(:/newPrefix/software logo.png);")
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.gridLayout.addWidget(self.label_logo, 0, 0, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_inbox = QtWidgets.QWidget()
        self.tab_inbox.setObjectName("tab_inbox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_inbox)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_inbox = QtWidgets.QGroupBox(self.tab_inbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_inbox.sizePolicy().hasHeightForWidth())
        self.groupBox_inbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_inbox.setFont(font)
        self.groupBox_inbox.setStyleSheet("background-color: #E3E3E3;\n"
"")
        self.groupBox_inbox.setTitle("")
        self.groupBox_inbox.setObjectName("groupBox_inbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_inbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_group_b = QtWidgets.QRadioButton(self.groupBox_inbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_group_b.sizePolicy().hasHeightForWidth())
        self.radioButton_group_b.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_group_b.setFont(font)
        self.radioButton_group_b.setStyleSheet("")
        self.radioButton_group_b.setCheckable(True)
        self.radioButton_group_b.setAutoExclusive(True)
        self.radioButton_group_b.setObjectName("radioButton_group_b")
        self.gridLayout_2.addWidget(self.radioButton_group_b, 3, 0, 1, 1)
        self.dateEdit_imap_since = QtWidgets.QDateEdit(self.groupBox_inbox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.dateEdit_imap_since.setFont(font)
        self.dateEdit_imap_since.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.dateEdit_imap_since.setWrapping(True)
        self.dateEdit_imap_since.setFrame(True)
        self.dateEdit_imap_since.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit_imap_since.setReadOnly(False)
        self.dateEdit_imap_since.setProperty("showGroupSeparator", False)
        self.dateEdit_imap_since.setCalendarPopup(True)
        self.dateEdit_imap_since.setObjectName("dateEdit_imap_since")
        self.gridLayout_2.addWidget(self.dateEdit_imap_since, 2, 1, 1, 1)
        self.label_version = QtWidgets.QLabel(self.groupBox_inbox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_version.setFont(font)
        self.label_version.setText("")
        self.label_version.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.gridLayout_2.addWidget(self.label_version, 3, 6, 1, 1, QtCore.Qt.AlignRight)
        self.radioButton_group_a = QtWidgets.QRadioButton(self.groupBox_inbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_group_a.sizePolicy().hasHeightForWidth())
        self.radioButton_group_a.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_group_a.setFont(font)
        self.radioButton_group_a.setStyleSheet("")
        self.radioButton_group_a.setCheckable(True)
        self.radioButton_group_a.setChecked(True)
        self.radioButton_group_a.setAutoExclusive(True)
        self.radioButton_group_a.setObjectName("radioButton_group_a")
        self.gridLayout_2.addWidget(self.radioButton_group_a, 2, 0, 1, 1)
        self.tableWidget_inbox = QtWidgets.QTableWidget(self.groupBox_inbox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.tableWidget_inbox.setFont(font)
        self.tableWidget_inbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.tableWidget_inbox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_inbox.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_inbox.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_inbox.setAlternatingRowColors(True)
        self.tableWidget_inbox.setShowGrid(False)
        self.tableWidget_inbox.setObjectName("tableWidget_inbox")
        self.tableWidget_inbox.setColumnCount(5)
        self.tableWidget_inbox.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_inbox.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_inbox.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_inbox.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_inbox.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_inbox.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_inbox.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_inbox.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_inbox.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_inbox.setItem(0, 2, item)
        self.tableWidget_inbox.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_inbox.horizontalHeader().setDefaultSectionSize(125)
        self.tableWidget_inbox.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.tableWidget_inbox, 8, 0, 1, 7)
        self.checkBox_delete_all = QtWidgets.QCheckBox(self.groupBox_inbox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.checkBox_delete_all.setFont(font)
        self.checkBox_delete_all.setObjectName("checkBox_delete_all")
        self.gridLayout_2.addWidget(self.checkBox_delete_all, 9, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_inbox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.pushButton_download_email = QtWidgets.QPushButton(self.groupBox_inbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_download_email.sizePolicy().hasHeightForWidth())
        self.pushButton_download_email.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_download_email.setFont(font)
        self.pushButton_download_email.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_download_email.setObjectName("pushButton_download_email")
        self.gridLayout_2.addWidget(self.pushButton_download_email, 3, 1, 1, 1)
        self.pushButton_delete = QtWidgets.QPushButton(self.groupBox_inbox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout_2.addWidget(self.pushButton_delete, 9, 0, 1, 1)
        self.label_email_status = QtWidgets.QLabel(self.groupBox_inbox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_email_status.setFont(font)
        self.label_email_status.setText("")
        self.label_email_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_email_status.setObjectName("label_email_status")
        self.gridLayout_2.addWidget(self.label_email_status, 9, 2, 1, 5)
        self.comboBox_date_sort = QtWidgets.QComboBox(self.groupBox_inbox)
        self.comboBox_date_sort.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_date_sort.setFont(font)
        self.comboBox_date_sort.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_date_sort.setObjectName("comboBox_date_sort")
        self.comboBox_date_sort.addItem("")
        self.comboBox_date_sort.addItem("")
        self.comboBox_date_sort.addItem("")
        self.comboBox_date_sort.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_date_sort, 2, 2, 1, 1)
        self.pushButton_fire_inbox_webhook = QtWidgets.QPushButton(self.groupBox_inbox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.pushButton_fire_inbox_webhook.setFont(font)
        self.pushButton_fire_inbox_webhook.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_fire_inbox_webhook.setObjectName("pushButton_fire_inbox_webhook")
        self.gridLayout_2.addWidget(self.pushButton_fire_inbox_webhook, 3, 2, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_inbox, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_inbox)
        self.groupBox.setStyleSheet("background-color: #E3E3E3;\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("border:none;")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_proxy_provider = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_proxy_provider.sizePolicy().hasHeightForWidth())
        self.pushButton_proxy_provider.setSizePolicy(sizePolicy)
        self.pushButton_proxy_provider.setMaximumSize(QtCore.QSize(270, 210))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_proxy_provider.setFont(font)
        self.pushButton_proxy_provider.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 7px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_proxy_provider.setFlat(False)
        self.pushButton_proxy_provider.setObjectName("pushButton_proxy_provider")
        self.gridLayout_5.addWidget(self.pushButton_proxy_provider, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 0, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("border:none;")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_original_recipient = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_original_recipient.sizePolicy().hasHeightForWidth())
        self.lineEdit_original_recipient.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.lineEdit_original_recipient.setFont(font)
        self.lineEdit_original_recipient.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_original_recipient.setFrame(False)
        self.lineEdit_original_recipient.setReadOnly(True)
        self.lineEdit_original_recipient.setClearButtonEnabled(False)
        self.lineEdit_original_recipient.setObjectName("lineEdit_original_recipient")
        self.gridLayout_6.addWidget(self.lineEdit_original_recipient, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setStyleSheet("border:none;")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 25))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_10.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 25))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_10.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.pushButton_forward = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_forward.sizePolicy().hasHeightForWidth())
        self.pushButton_forward.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.pushButton_forward.setFont(font)
        self.pushButton_forward.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_forward.setObjectName("pushButton_forward")
        self.gridLayout_10.addWidget(self.pushButton_forward, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_3.addWidget(self.groupBox_8, 6, 0, 1, 1)
        self.textBrowser_show_email = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_show_email.setMinimumSize(QtCore.QSize(600, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.textBrowser_show_email.setFont(font)
        self.textBrowser_show_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_show_email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhMultiLine)
        self.textBrowser_show_email.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_show_email.setOpenExternalLinks(True)
        self.textBrowser_show_email.setOpenLinks(False)
        self.textBrowser_show_email.setObjectName("textBrowser_show_email")
        self.gridLayout_3.addWidget(self.textBrowser_show_email, 3, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_inbox, "")
        self.tab_compose = QtWidgets.QWidget()
        self.tab_compose.setObjectName("tab_compose")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_compose)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 3, 3, 1, 1)
        self.pushButton_attachments = QtWidgets.QPushButton(self.tab_compose)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_attachments.setFont(font)
        self.pushButton_attachments.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_attachments.setObjectName("pushButton_attachments")
        self.gridLayout_4.addWidget(self.pushButton_attachments, 24, 3, 1, 1)
        self.textBrowser_compose = QtWidgets.QTextBrowser(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_compose.sizePolicy().hasHeightForWidth())
        self.textBrowser_compose.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.textBrowser_compose.setFont(font)
        self.textBrowser_compose.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_compose.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_compose.setReadOnly(False)
        self.textBrowser_compose.setObjectName("textBrowser_compose")
        self.gridLayout_4.addWidget(self.textBrowser_compose, 1, 0, 24, 2)
        self.label_compose_status = QtWidgets.QLabel(self.tab_compose)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_compose_status.setFont(font)
        self.label_compose_status.setText("")
        self.label_compose_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_compose_status.setObjectName("label_compose_status")
        self.gridLayout_4.addWidget(self.label_compose_status, 26, 0, 1, 4)
        self.progressBar_compose = QtWidgets.QProgressBar(self.tab_compose)
        self.progressBar_compose.setProperty("value", 0)
        self.progressBar_compose.setObjectName("progressBar_compose")
        self.gridLayout_4.addWidget(self.progressBar_compose, 27, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 23, 3, 1, 1)
        self.pushButton_attachments_clear = QtWidgets.QPushButton(self.tab_compose)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.pushButton_attachments_clear.setFont(font)
        self.pushButton_attachments_clear.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_attachments_clear.setObjectName("pushButton_attachments_clear")
        self.gridLayout_4.addWidget(self.pushButton_attachments_clear, 25, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 8, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 5, 3, 1, 1)
        self.checkBox_email_tracking = QtWidgets.QCheckBox(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_email_tracking.sizePolicy().hasHeightForWidth())
        self.checkBox_email_tracking.setSizePolicy(sizePolicy)
        self.checkBox_email_tracking.setObjectName("checkBox_email_tracking")
        self.gridLayout_4.addWidget(self.checkBox_email_tracking, 14, 3, 1, 1)
        self.pushButton_compose_zoomIn = QtWidgets.QPushButton(self.tab_compose)
        self.pushButton_compose_zoomIn.setMaximumSize(QtCore.QSize(30, 25))
        self.pushButton_compose_zoomIn.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_compose_zoomIn.setObjectName("pushButton_compose_zoomIn")
        self.gridLayout_4.addWidget(self.pushButton_compose_zoomIn, 11, 2, 1, 1)
        self.lineEdit_subject = QtWidgets.QLineEdit(self.tab_compose)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.lineEdit_subject.setFont(font)
        self.lineEdit_subject.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_subject.setFrame(False)
        self.lineEdit_subject.setClearButtonEnabled(True)
        self.lineEdit_subject.setObjectName("lineEdit_subject")
        self.gridLayout_4.addWidget(self.lineEdit_subject, 0, 1, 1, 1)
        self.lineEdit_delay_between_emails = QtWidgets.QLineEdit(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_delay_between_emails.sizePolicy().hasHeightForWidth())
        self.lineEdit_delay_between_emails.setSizePolicy(sizePolicy)
        self.lineEdit_delay_between_emails.setMinimumSize(QtCore.QSize(140, 24))
        self.lineEdit_delay_between_emails.setMaximumSize(QtCore.QSize(140, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.lineEdit_delay_between_emails.setFont(font)
        self.lineEdit_delay_between_emails.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_delay_between_emails.setMaxLength(9)
        self.lineEdit_delay_between_emails.setFrame(False)
        self.lineEdit_delay_between_emails.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_delay_between_emails.setObjectName("lineEdit_delay_between_emails")
        self.gridLayout_4.addWidget(self.lineEdit_delay_between_emails, 8, 3, 1, 1)
        self.checkBox_remove_email_from_target = QtWidgets.QCheckBox(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_remove_email_from_target.sizePolicy().hasHeightForWidth())
        self.checkBox_remove_email_from_target.setSizePolicy(sizePolicy)
        self.checkBox_remove_email_from_target.setObjectName("checkBox_remove_email_from_target")
        self.gridLayout_4.addWidget(self.checkBox_remove_email_from_target, 16, 3, 1, 1)
        self.checkBox_check_for_blocks = QtWidgets.QCheckBox(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_check_for_blocks.sizePolicy().hasHeightForWidth())
        self.checkBox_check_for_blocks.setSizePolicy(sizePolicy)
        self.checkBox_check_for_blocks.setObjectName("checkBox_check_for_blocks")
        self.gridLayout_4.addWidget(self.checkBox_check_for_blocks, 17, 3, 1, 1)
        self.pushButton_compose_zoomOut = QtWidgets.QPushButton(self.tab_compose)
        self.pushButton_compose_zoomOut.setMaximumSize(QtCore.QSize(30, 25))
        self.pushButton_compose_zoomOut.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_compose_zoomOut.setObjectName("pushButton_compose_zoomOut")
        self.gridLayout_4.addWidget(self.pushButton_compose_zoomOut, 12, 2, 1, 1)
        self.pushButton_clear_compose = QtWidgets.QPushButton(self.tab_compose)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.pushButton_clear_compose.setFont(font)
        self.pushButton_clear_compose.setStyleSheet("QPushButton {\n"
"    background-image: url(:/newPrefix/software logo.png);\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_clear_compose.setObjectName("pushButton_clear_compose")
        self.gridLayout_4.addWidget(self.pushButton_clear_compose, 11, 3, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.radioButton_html = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_html.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_html.sizePolicy().hasHeightForWidth())
        self.radioButton_html.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_html.setFont(font)
        self.radioButton_html.setObjectName("radioButton_html")
        self.gridLayout_9.addWidget(self.radioButton_html, 1, 0, 1, 1)
        self.radioButton_plain_text = QtWidgets.QRadioButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_plain_text.sizePolicy().hasHeightForWidth())
        self.radioButton_plain_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_plain_text.setFont(font)
        self.radioButton_plain_text.setChecked(True)
        self.radioButton_plain_text.setObjectName("radioButton_plain_text")
        self.gridLayout_9.addWidget(self.radioButton_plain_text, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_6, 9, 3, 1, 1)
        self.pushButton_compose_send_cancel = QtWidgets.QPushButton(self.tab_compose)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_compose_send_cancel.setFont(font)
        self.pushButton_compose_send_cancel.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #03506f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #c5d7bd, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_compose_send_cancel.setObjectName("pushButton_compose_send_cancel")
        self.gridLayout_4.addWidget(self.pushButton_compose_send_cancel, 22, 3, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton_campaign_group_b = QtWidgets.QRadioButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_campaign_group_b.sizePolicy().hasHeightForWidth())
        self.radioButton_campaign_group_b.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_campaign_group_b.setFont(font)
        self.radioButton_campaign_group_b.setObjectName("radioButton_campaign_group_b")
        self.gridLayout_7.addWidget(self.radioButton_campaign_group_b, 1, 0, 1, 1)
        self.radioButton_campaign_group_a = QtWidgets.QRadioButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_campaign_group_a.sizePolicy().hasHeightForWidth())
        self.radioButton_campaign_group_a.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_campaign_group_a.setFont(font)
        self.radioButton_campaign_group_a.setChecked(True)
        self.radioButton_campaign_group_a.setObjectName("radioButton_campaign_group_a")
        self.gridLayout_7.addWidget(self.radioButton_campaign_group_a, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 3, 1, 1)
        self.lineEdit_num_per_address = QtWidgets.QLineEdit(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_num_per_address.sizePolicy().hasHeightForWidth())
        self.lineEdit_num_per_address.setSizePolicy(sizePolicy)
        self.lineEdit_num_per_address.setMinimumSize(QtCore.QSize(140, 24))
        self.lineEdit_num_per_address.setMaximumSize(QtCore.QSize(140, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.lineEdit_num_per_address.setFont(font)
        self.lineEdit_num_per_address.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_num_per_address.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_num_per_address.setMaxLength(4)
        self.lineEdit_num_per_address.setFrame(False)
        self.lineEdit_num_per_address.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_num_per_address.setObjectName("lineEdit_num_per_address")
        self.gridLayout_4.addWidget(self.lineEdit_num_per_address, 6, 3, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButton_reply = QtWidgets.QRadioButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_reply.sizePolicy().hasHeightForWidth())
        self.radioButton_reply.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_reply.setFont(font)
        self.radioButton_reply.setChecked(False)
        self.radioButton_reply.setAutoExclusive(True)
        self.radioButton_reply.setObjectName("radioButton_reply")
        self.gridLayout_8.addWidget(self.radioButton_reply, 0, 0, 1, 1)
        self.radioButton_send_campaign = QtWidgets.QRadioButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_send_campaign.sizePolicy().hasHeightForWidth())
        self.radioButton_send_campaign.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_send_campaign.setFont(font)
        self.radioButton_send_campaign.setChecked(True)
        self.radioButton_send_campaign.setObjectName("radioButton_send_campaign")
        self.gridLayout_8.addWidget(self.radioButton_send_campaign, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 3, 1, 1)
        self.checkBox_compose_preview = QtWidgets.QCheckBox(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_compose_preview.sizePolicy().hasHeightForWidth())
        self.checkBox_compose_preview.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_compose_preview.setFont(font)
        self.checkBox_compose_preview.setObjectName("checkBox_compose_preview")
        self.gridLayout_4.addWidget(self.checkBox_compose_preview, 10, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 8, 2, 1, 1)
        self.comboBox_attachments = QtWidgets.QComboBox(self.tab_compose)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(15)
        self.comboBox_attachments.setFont(font)
        self.comboBox_attachments.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_attachments.setFrame(False)
        self.comboBox_attachments.setObjectName("comboBox_attachments")
        self.gridLayout_4.addWidget(self.comboBox_attachments, 25, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.tab_compose)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_compose)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.pushButton_send = QtWidgets.QPushButton(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_send.sizePolicy().hasHeightForWidth())
        self.pushButton_send.setSizePolicy(sizePolicy)
        self.pushButton_send.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_send.setFont(font)
        self.pushButton_send.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #03506f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #c5d7bd, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_send.setObjectName("pushButton_send")
        self.gridLayout_4.addWidget(self.pushButton_send, 21, 3, 1, 1)
        self.lineEdit_number_of_threads = QtWidgets.QLineEdit(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_number_of_threads.sizePolicy().hasHeightForWidth())
        self.lineEdit_number_of_threads.setSizePolicy(sizePolicy)
        self.lineEdit_number_of_threads.setMinimumSize(QtCore.QSize(140, 24))
        self.lineEdit_number_of_threads.setMaximumSize(QtCore.QSize(140, 24))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.lineEdit_number_of_threads.setFont(font)
        self.lineEdit_number_of_threads.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_number_of_threads.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_number_of_threads.setMaxLength(4)
        self.lineEdit_number_of_threads.setFrame(False)
        self.lineEdit_number_of_threads.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_number_of_threads.setObjectName("lineEdit_number_of_threads")
        self.gridLayout_4.addWidget(self.lineEdit_number_of_threads, 4, 3, 1, 1)
        self.pushButton_test = QtWidgets.QPushButton(self.tab_compose)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.pushButton_test.setFont(font)
        self.pushButton_test.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_test.setObjectName("pushButton_test")
        self.gridLayout_4.addWidget(self.pushButton_test, 12, 3, 1, 1)
        self.label_delay_between_emails = QtWidgets.QLabel(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_delay_between_emails.sizePolicy().hasHeightForWidth())
        self.label_delay_between_emails.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_delay_between_emails.setFont(font)
        self.label_delay_between_emails.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_delay_between_emails.setObjectName("label_delay_between_emails")
        self.gridLayout_4.addWidget(self.label_delay_between_emails, 7, 3, 1, 1)
        self.checkBox_enable_webhook = QtWidgets.QCheckBox(self.tab_compose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_enable_webhook.sizePolicy().hasHeightForWidth())
        self.checkBox_enable_webhook.setSizePolicy(sizePolicy)
        self.checkBox_enable_webhook.setObjectName("checkBox_enable_webhook")
        self.gridLayout_4.addWidget(self.checkBox_enable_webhook, 15, 3, 1, 1)
        self.checkBox_add_custom_hostname = QtWidgets.QCheckBox(self.tab_compose)
        self.checkBox_add_custom_hostname.setObjectName("checkBox_add_custom_hostname")
        self.gridLayout_4.addWidget(self.checkBox_add_custom_hostname, 13, 3, 1, 1)
        self.tabWidget.addTab(self.tab_compose, "")
        self.tab_database = QtWidgets.QWidget()
        self.tab_database.setObjectName("tab_database")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_database)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tableView_database = QtWidgets.QTableView(self.tab_database)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.tableView_database.setFont(font)
        self.tableView_database.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.tableView_database.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableView_database.setAlternatingRowColors(True)
        self.tableView_database.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_database.setObjectName("tableView_database")
        self.tableView_database.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView_database.horizontalHeader().setDefaultSectionSize(150)
        self.tableView_database.horizontalHeader().setStretchLastSection(False)
        self.tableView_database.verticalHeader().setVisible(False)
        self.gridLayout_13.addWidget(self.tableView_database, 5, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_database)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_7)
        self.formLayout.setObjectName("formLayout")
        self.radioButton_db_groupa = QtWidgets.QRadioButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_db_groupa.setFont(font)
        self.radioButton_db_groupa.setChecked(True)
        self.radioButton_db_groupa.setObjectName("radioButton_db_groupa")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radioButton_db_groupa)
        self.radioButton_db_groupb = QtWidgets.QRadioButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_db_groupb.setFont(font)
        self.radioButton_db_groupb.setObjectName("radioButton_db_groupb")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.radioButton_db_groupb)
        self.radioButton_db_target = QtWidgets.QRadioButton(self.groupBox_7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_db_target.setFont(font)
        self.radioButton_db_target.setObjectName("radioButton_db_target")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.radioButton_db_target)
        self.pushButton_load_db = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_load_db.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_load_db.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_load_db.setFont(font)
        self.pushButton_load_db.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_load_db.setObjectName("pushButton_load_db")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pushButton_load_db)
        self.checkBox_database_group_a = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_database_group_a.setChecked(True)
        self.checkBox_database_group_a.setObjectName("checkBox_database_group_a")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.checkBox_database_group_a)
        self.checkBox_database_group_b = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_database_group_b.setChecked(True)
        self.checkBox_database_group_b.setObjectName("checkBox_database_group_b")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.checkBox_database_group_b)
        self.checkBox_database_target = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_database_target.setChecked(True)
        self.checkBox_database_target.setObjectName("checkBox_database_target")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.checkBox_database_target)
        self.pushButton_remove_row = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_remove_row.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_remove_row.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_remove_row.setFont(font)
        self.pushButton_remove_row.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_remove_row.setObjectName("pushButton_remove_row")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pushButton_remove_row)
        self.pushButton_add_row = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_add_row.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_add_row.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add_row.setFont(font)
        self.pushButton_add_row.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_add_row.setObjectName("pushButton_add_row")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pushButton_add_row)
        self.gridLayout_13.addWidget(self.groupBox_7, 5, 1, 1, 3)
        self.tabWidget.addTab(self.tab_database, "")
        self.tab_configuration = QtWidgets.QWidget()
        self.tab_configuration.setObjectName("tab_configuration")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_configuration)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_configuration)
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 16777212))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet("")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_7 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_14.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_valid_input = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_valid_input.setFont(font)
        self.label_valid_input.setAlignment(QtCore.Qt.AlignCenter)
        self.label_valid_input.setWordWrap(True)
        self.label_valid_input.setObjectName("label_valid_input")
        self.gridLayout_14.addWidget(self.label_valid_input, 6, 0, 1, 2, QtCore.Qt.AlignVCenter)
        self.label_8 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_14.addWidget(self.label_8, 3, 0, 1, 1)
        self.lineEdit_email_tracking_campaign_name = QtWidgets.QLineEdit(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_email_tracking_campaign_name.setFont(font)
        self.lineEdit_email_tracking_campaign_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_email_tracking_campaign_name.setFrame(False)
        self.lineEdit_email_tracking_campaign_name.setClearButtonEnabled(True)
        self.lineEdit_email_tracking_campaign_name.setObjectName("lineEdit_email_tracking_campaign_name")
        self.gridLayout_14.addWidget(self.lineEdit_email_tracking_campaign_name, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_14.addWidget(self.label_9, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_email_tracking_analytics_account = QtWidgets.QLineEdit(self.groupBox_9)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_email_tracking_analytics_account.setFont(font)
        self.lineEdit_email_tracking_analytics_account.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_email_tracking_analytics_account.setFrame(False)
        self.lineEdit_email_tracking_analytics_account.setClearButtonEnabled(True)
        self.lineEdit_email_tracking_analytics_account.setObjectName("lineEdit_email_tracking_analytics_account")
        self.gridLayout_14.addWidget(self.lineEdit_email_tracking_analytics_account, 1, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_9, 2, 1, 1, 2)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_configuration)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.lineEdit_webhook_link = QtWidgets.QLineEdit(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_webhook_link.setFont(font)
        self.lineEdit_webhook_link.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_webhook_link.setFrame(False)
        self.lineEdit_webhook_link.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_webhook_link.setObjectName("lineEdit_webhook_link")
        self.gridLayout_16.addWidget(self.lineEdit_webhook_link, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_16.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEdit_target_blacklist = QtWidgets.QLineEdit(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_target_blacklist.setFont(font)
        self.lineEdit_target_blacklist.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_target_blacklist.setFrame(False)
        self.lineEdit_target_blacklist.setObjectName("lineEdit_target_blacklist")
        self.gridLayout_16.addWidget(self.lineEdit_target_blacklist, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_16.addWidget(self.label_11, 1, 0, 1, 1)
        self.checkBox_responses_webhook = QtWidgets.QCheckBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_responses_webhook.setFont(font)
        self.checkBox_responses_webhook.setObjectName("checkBox_responses_webhook")
        self.gridLayout_16.addWidget(self.checkBox_responses_webhook, 2, 1, 1, 1)
        self.pushButton_clear_cached_targets = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_clear_cached_targets.setMinimumSize(QtCore.QSize(290, 0))
        self.pushButton_clear_cached_targets.setMaximumSize(QtCore.QSize(290, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_clear_cached_targets.setFont(font)
        self.pushButton_clear_cached_targets.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_clear_cached_targets.setObjectName("pushButton_clear_cached_targets")
        self.gridLayout_16.addWidget(self.pushButton_clear_cached_targets, 3, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_10, 3, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem3, 6, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem4, 6, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem5, 8, 2, 1, 1)
        self.pushButton_configuration_save = QtWidgets.QPushButton(self.tab_configuration)
        self.pushButton_configuration_save.setEnabled(True)
        self.pushButton_configuration_save.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.pushButton_configuration_save.setFont(font)
        self.pushButton_configuration_save.setStyleSheet("QPushButton {\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #4B7DAD\n"
"        );\n"
"    padding: 5px 28px;\n"
"    color: rgb(255, 255, 255);\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #709fb0\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    }")
        self.pushButton_configuration_save.setObjectName("pushButton_configuration_save")
        self.gridLayout_15.addWidget(self.pushButton_configuration_save, 6, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem6, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_configuration, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.pushButton_clear_compose.clicked.connect(self.textBrowser_compose.clear)
        self.pushButton_attachments_clear.clicked.connect(self.comboBox_attachments.clear)
        self.pushButton_3.clicked.connect(self.textBrowser_show_email.zoomIn)
        self.pushButton_4.clicked.connect(self.textBrowser_show_email.zoomOut)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GMonster"))
        self.radioButton_group_b.setText(_translate("MainWindow", "Group B"))
        self.radioButton_group_a.setText(_translate("MainWindow", "Group A"))
        item = self.tableWidget_inbox.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FROM"))
        item = self.tableWidget_inbox.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SUBJECT"))
        item = self.tableWidget_inbox.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "DATE"))
        __sortingEnabled = self.tableWidget_inbox.isSortingEnabled()
        self.tableWidget_inbox.setSortingEnabled(False)
        self.tableWidget_inbox.setSortingEnabled(__sortingEnabled)
        self.checkBox_delete_all.setText(_translate("MainWindow", "Delete All"))
        self.label_5.setText(_translate("MainWindow", "ADDRESS GROUP"))
        self.pushButton_download_email.setText(_translate("MainWindow", "DOWNLOAD"))
        self.pushButton_delete.setText(_translate("MainWindow", "DELETE"))
        self.comboBox_date_sort.setItemText(0, _translate("MainWindow", "Latest first"))
        self.comboBox_date_sort.setItemText(1, _translate("MainWindow", "Earliest first"))
        self.comboBox_date_sort.setItemText(2, _translate("MainWindow", "a - z"))
        self.comboBox_date_sort.setItemText(3, _translate("MainWindow", "z - a"))
        self.pushButton_fire_inbox_webhook.setText(_translate("MainWindow", "FIRE WEBHOOK"))
        self.pushButton_proxy_provider.setText(_translate("MainWindow", "More GMonster Proxies"))
        self.label.setText(_translate("MainWindow", "ORIGINAL RECIPIENT:"))
        self.pushButton_3.setText(_translate("MainWindow", "+"))
        self.pushButton_4.setText(_translate("MainWindow", "-"))
        self.pushButton_forward.setText(_translate("MainWindow", "FORWARD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_inbox), _translate("MainWindow", "Inbox"))
        self.label_3.setText(_translate("MainWindow", "NUMBER OF THREADS"))
        self.pushButton_attachments.setText(_translate("MainWindow", "ATTACHMENTS"))
        self.pushButton_attachments_clear.setText(_translate("MainWindow", "CLEAR LIST"))
        self.label_2.setText(_translate("MainWindow", "NUM EMAILS PER ACCOUNT"))
        self.checkBox_email_tracking.setText(_translate("MainWindow", "Enable Email Tracking"))
        self.pushButton_compose_zoomIn.setText(_translate("MainWindow", "+"))
        self.lineEdit_delay_between_emails.setText(_translate("MainWindow", "5-20"))
        self.lineEdit_delay_between_emails.setPlaceholderText(_translate("MainWindow", "Enter a Range"))
        self.checkBox_remove_email_from_target.setText(_translate("MainWindow", "Remove Email From Target"))
        self.checkBox_check_for_blocks.setText(_translate("MainWindow", "Check for blocks"))
        self.pushButton_compose_zoomOut.setText(_translate("MainWindow", "-"))
        self.pushButton_clear_compose.setText(_translate("MainWindow", "CLEAR TEXT"))
        self.radioButton_html.setText(_translate("MainWindow", "Html"))
        self.radioButton_plain_text.setText(_translate("MainWindow", "Plain Text"))
        self.pushButton_compose_send_cancel.setText(_translate("MainWindow", "CANCEL"))
        self.radioButton_campaign_group_b.setText(_translate("MainWindow", "Group B"))
        self.radioButton_campaign_group_a.setText(_translate("MainWindow", "Group A"))
        self.lineEdit_num_per_address.setPlaceholderText(_translate("MainWindow", "ENTER NUMBER"))
        self.radioButton_reply.setText(_translate("MainWindow", "Reply"))
        self.radioButton_send_campaign.setText(_translate("MainWindow", "Send Campaign"))
        self.checkBox_compose_preview.setText(_translate("MainWindow", "Preview"))
        self.label_6.setText(_translate("MainWindow", "CAMPAIGN SETTINGS"))
        self.label_4.setText(_translate("MainWindow", "SUBJECT:"))
        self.pushButton_send.setText(_translate("MainWindow", "SEND"))
        self.lineEdit_number_of_threads.setPlaceholderText(_translate("MainWindow", "ENTER NUMBER"))
        self.pushButton_test.setText(_translate("MainWindow", "TEST"))
        self.label_delay_between_emails.setText(_translate("MainWindow", "DELAY BETWEEN EMAILS"))
        self.checkBox_enable_webhook.setText(_translate("MainWindow", "Enable Webhook"))
        self.checkBox_add_custom_hostname.setText(_translate("MainWindow", "Custom Hostname"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_compose), _translate("MainWindow", "Compose"))
        self.radioButton_db_groupa.setText(_translate("MainWindow", "Group A"))
        self.radioButton_db_groupb.setText(_translate("MainWindow", "Group B"))
        self.radioButton_db_target.setText(_translate("MainWindow", "Target"))
        self.pushButton_load_db.setText(_translate("MainWindow", "LOAD FILE"))
        self.checkBox_database_group_a.setText(_translate("MainWindow", "Group A"))
        self.checkBox_database_group_b.setText(_translate("MainWindow", "Group B"))
        self.checkBox_database_target.setText(_translate("MainWindow", "Target"))
        self.pushButton_remove_row.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_add_row.setText(_translate("MainWindow", "ADD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_database), _translate("MainWindow", "Database"))
        self.label_7.setText(_translate("MainWindow", "Analytics Account"))
        self.label_valid_input.setText(_translate("MainWindow", "Campaign Name field: letters, numbers and \"_\" only. (no spaces)"))
        self.label_8.setText(_translate("MainWindow", "Campaign Name"))
        self.label_9.setText(_translate("MainWindow", "Email Tracking Configuration"))
        self.label_10.setText(_translate("MainWindow", "Webhook Link"))
        self.label_11.setText(_translate("MainWindow", "Target Blacklist"))
        self.checkBox_responses_webhook.setText(_translate("MainWindow", "Responses Webhook Enabled"))
        self.pushButton_clear_cached_targets.setText(_translate("MainWindow", "Clear Cached Targets from DB"))
        self.pushButton_configuration_save.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_configuration), _translate("MainWindow", "Configuration"))
import logo_rc
